FROM node:lts

# Set development environment
ENV NODE_ENV="development"

WORKDIR /app
ARG CQA_VERSION=3.0.3
ADD https://releases.clones-ai.com/cqa/clones-quality-agent-linux-x64-package-v${CQA_VERSION}.tar.gz ./cqa-package.tar.gz
RUN mkdir ./cqa && \
    tar -xzf cqa-package.tar.gz -C ./cqa && \
    chmod +x ./cqa/clones-quality-agent-linux-x64-v${CQA_VERSION} && \
    ln -s cqa/clones-quality-agent-linux-x64-v${CQA_VERSION} clones-quality-agent && \
    rm cqa-package.tar.gz

COPY . .

# Install packages needed to build node modules
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  node-gyp \
  pkg-config \
  python-is-python3 \
  ffmpeg \
  libavcodec-dev \
  libavformat-dev \
  libavutil-dev \
  libswscale-dev

RUN npm install

EXPOSE 8001
