FROM node:lts

# Set development environment
ENV NODE_ENV="development"

WORKDIR /app
ARG CQA_VERSION=2.0.3
ADD https://github.com/clones-ai/clones-quality-agent/releases/download/v${CQA_VERSION}/clones-quality-agent-linux-x64 ./clones-quality-agent
RUN chmod +x clones-quality-agent

COPY . .

# Install packages needed to build node modules
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  node-gyp \
  pkg-config \
  python-is-python3 \
  ffmpeg \
  libavcodec-dev \
  libavformat-dev \
  libavutil-dev \
  libswscale-dev

RUN npm install

EXPOSE 8001
