# fly.toml app configuration file for the test environment
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clones-backend-test'
primary_region = 'lax'

[env]
  NODE_ENV = "test"

[processes]
  app = "node ./build/server.js"

[[services]]
  internal_port = 8001
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1 

[mounts]
  source = "upload_volume"
  destination = "/app/uploads"
