# fly.toml app configuration file for the test environment
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clones-backend-test'
primary_region = 'cdg'

[env]
  NODE_ENV = "test"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1 

[mounts]
  source="uploads"
  destination="/app/uploads"