# fly.toml app configuration file for the prod environment
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "clones-mongodb-prod"
  primary_region = "lax"

  [build]
    image = "mongo:7.0"

  [[mounts]]
    auto_extend_size_increment = "1GB"
    auto_extend_size_limit = "5GB"
    auto_extend_size_threshold = 90
    destination = "/data/db"
    initial_size = "10gb"
    source = "mongodb_data"

  [processes]
  app = "mongod --ipv6 --bind_ip 0.0.0.0,:: --port 27017 --auth --dbpath /data/db --logappend"

  [[services]]
    auto_start_machines = true
    auto_stop_machines = false
    internal_port = 27017
    min_machines_running = 1
    protocol = "tcp"
    processes = [ "app" ]

  [[vm]]
    cpu_kind = "shared"
    cpus = 2
    memory = "2gb"