[package]
name = "reward-pool"
version = "0.1.0"
description = "Reward distribution system for Clones AI platform"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "reward_pool"

[dependencies]
solana-program = "=1.13.0"
borsh = "0.9.3"
borsh-derive = "0.9.3"
thiserror = "1.0.40" 