import { type Document, model, Schema } from 'mongoose'

export interface ITransactionSession extends Document {
  sessionId: string // UUID generated by desktop
  sessionToken: string // Existing wallet token for security
  transactionType: 'createFactory' | 'fundPool' | 'claimRewards' | 'createAndFundFactory'
  status: 'pending' | 'completed' | 'failed' | 'cancelled'
  txHash?: string // Transaction hash if successful
  error?: string // Error message if failed
  transactionParams?: any // Transaction parameters for debugging
  createdAt: Date
  updatedAt: Date
  expiresAt: Date // Expires after 3 minutes
}

const TransactionSessionSchema = new Schema<ITransactionSession>(
  {
    sessionId: {
      type: String,
      required: true,
      unique: true,
      index: true
    },
    sessionToken: {
      type: String,
      required: true,
      index: true
    },
    transactionType: {
      type: String,
      required: true,
      enum: ['createFactory', 'fundPool', 'claimRewards', 'createAndFundFactory']
    },
    status: {
      type: String,
      required: true,
      default: 'pending',
      enum: ['pending', 'completed', 'failed', 'cancelled']
    },
    txHash: {
      type: String,
      required: false
    },
    error: {
      type: String,
      required: false
    },
    transactionParams: {
      type: Schema.Types.Mixed,
      required: false
    },
    createdAt: {
      type: Date,
      default: Date.now
    },
    updatedAt: {
      type: Date,
      default: Date.now
    },
    expiresAt: {
      type: Date,
      required: true,
      index: { expireAfterSeconds: 0 } // MongoDB TTL index
    }
  },
  { collection: 'transaction_sessions' }
)

// Middleware to update updatedAt
TransactionSessionSchema.pre('save', function (next) {
  this.updatedAt = new Date()
  next()
})

// Compound indexes for frequent queries
TransactionSessionSchema.index({ sessionToken: 1, status: 1 })
TransactionSessionSchema.index({ status: 1, createdAt: -1 })

export const TransactionSessionModel = model<ITransactionSession>(
  'TransactionSession',
  TransactionSessionSchema
)
